### ISSUE TITLE
Problem with assembly

### ISSUE THREAD

**Issue by typhon666-77** [kr55/ssiscataloger#1]
Hello, i'm trying to use the tool but i got an error message

![image](https://user-images.githubusercontent.com/82462090/114582871-4bb80f00-9c81-11eb-9603-34f8ace3c29f.png)

I didn't see any prerequisites before installing the tool. Is something else needed to be installed before ssiscataloger ?

**Comment by kr55** [comment]
Hello, Thank you for reporting this issue. 
There were a couple of missing physical assembly references in the recent version of the tool. This has caused due to broken references at the time of the build. I hopefully have fixed this and deployed the latest version (1.2.7).
 You would need to download and reinstall the tool to get it working.
Could you please try it and let me know if it is working now?

I will close this issue based on your feedback.

**Comment by typhon666-77** [comment]
Hello again, it's working.
Thanks a lot 👍

**Comment by kr55** [comment]
Great! Kindly rate your experience and [write a review](https://marketplace.visualstudio.com/items?itemName=AzureOps.ssiscataloger&ssr=false#review-details) so that others can benefit from it.
